using System;
using System.Collections.Generic;
using System.Linq;
using Transpiler.Parse;

namespace Transpiler.Analysis
{
    public record AzAppExpn(IAzFuncExpn Function,
                            IAzFuncExpn Argument,
                            IAzTypeExpn Type,
                            CodePosition Position) : IAzFuncExpn, IAzPattern
    {
        public static IAzFuncExpn Analyze(Scope scope,
                                          NameProvider names,
                                          TvProvider tvs,
                                          PsArbExpn node)
        {
            var subexpns = node.Children.Select(c => IAzFuncExpn.Analyze(scope, names, tvs, c)).ToList();

            // Zero subexpressions (illegal).
            if (subexpns.Count == 0)
            {
                throw new NotImplementedException();
            }

            // One subexpression.
            if (subexpns.Count == 1)
            {
                if (subexpns[0] is AzSymbolExpn symExpn1)
                {
                    return symExpn1 with { Fixity = eFixity.Prefix };
                }
                return subexpns[0];
            }

            // Two subexpressions and the first is an infix operator.
            if ((subexpns.Count == 2) &&
                subexpns[0] is AzSymbolExpn op1 &&
                op1.Definition.Fixity == eFixity.Infix)
            {
                var param = new AzParam(names.Next, IsAutoGenerated: true, tvs.Next, op1.Position);
                var symbol = new AzSymbolExpn(param, param.Type, op1.Position);
                var innerApp = new AzAppExpn(op1, symbol, tvs.Next, op1.Position);
                var outerApp = new AzAppExpn(innerApp, subexpns[1], tvs.Next, op1.Position);

                return new AzLambdaExpn(param, outerApp, tvs.Next, op1.Position);
            }

            // Three subexpressions and the second is an infix operator.
            if ((subexpns.Count == 3) &&
                subexpns[1] is AzSymbolExpn symExpn &&
                symExpn.Fixity == eFixity.Infix)
            {
                var op = subexpns[1];
                var app2 = new AzAppExpn(op, subexpns[0], tvs.Next, op.Position);
                app2 = new AzAppExpn(app2, subexpns[2], tvs.Next, op.Position);
                return app2;
            }

            // Multiple subexpressions.
            IAzFuncExpn app = subexpns[0];
            var p = app.Position;
            for (int i = 1; i < subexpns.Count; i++)
            {
                if (subexpns[i] is AzSymbolExpn opi &&
                    opi.Fixity != eFixity.Prefix)
                {
                    app = new AzAppExpn(subexpns[i], app, tvs.Next, subexpns[i].Position);
                }
                else
                {
                    app = new AzAppExpn(app, subexpns[i], tvs.Next, app.Position);
                }
            }

            return app;
        }

        public ConstraintSet Constrain(TvProvider provider, Scope scope)
        {
            var csf = Function.Constrain(provider, scope);
            var csx = Argument.Constrain(provider, scope);

            var p = CodePosition.Null;
            var lamType = new AzTypeLambdaExpn(Argument.Type, Type, p);
            var cfx = new Constraint(Function.Type, lamType, Position);

            return IConstraintSet.Union(cfx, csf, csx);
        }

        public IReadOnlyList<IAzFuncNode> GetSubnodes()
        {
            return this.ToArr().Concat(Function.GetSubnodes()).Concat(Argument.GetSubnodes()).ToList();
        }

        public string Print(int i)
        {
            return string.Format("({0} {1})", Function.Print(i), Argument.Print(i));
        }


        IAzPattern IAzPattern.SubstituteType(Substitution s) => SubstituteType(s);
        IAzFuncExpn IAzFuncExpn.SubstituteType(Substitution s) => SubstituteType(s);

        public AzAppExpn SubstituteType(Substitution s)
        {
            return new AzAppExpn(Function.SubstituteType(s),
                                 Argument.SubstituteType(s),
                                 Type.Substitute(s),
                                 Position);
        }

        public override string ToString() => Print(0);
    }
}
