using Transpiler.Analysis;

namespace Transpiler.Generate
{
    public record GnParam(string Name,
                          bool IsAutoGenerated) : IGnPattern, IGnFuncDefn
    {
        public static GnParam Prepare(IScope scope, AzParam param)
        {
            return new(param.Name, param.IsAutoGenerated);
        }

        public string Generate(int i, NameProvider names, ref string s)
        {
            return Generate();
        }

        public string Generate()
        {
            return IsAutoGenerated
                ? Name
                : Name.SafeName();
        }
    }
}
